apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-frontend-deployment
  namespace: mcp
  labels:
    app: mcp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-frontend
  template:
    metadata:
      labels:
        app: mcp-frontend
    spec:
      containers:
      - name: mcp-frontend
        image: ghcr.io/jwjinn/mcp-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://mcp-api-agent-service.mcp.svc.cluster.local:80"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-frontend-service
  namespace: mcp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    # 외부에서 접속할 포트를 30080으로 고정합니다.
    nodePort: 30080
  selector:
    app: mcp-frontend
